### ISSUE TITLE
déconnection après changement de transporteur

### ISSUE THREAD

**Issue by nicoxygen** [Klemart3D/changecarrier#3]
bonjour depuis quelques temps j'ai un soucis avec votre module je suis sous prestashop 1.6.1.24
et quand je change le transporteur sur une commande, l'administration se déconnecte et passe sur la page d'accueil de l'administration en http, alors qu'à l'origine nous sommes connectés en https 
message:
Le protocole SSL est activé. Veuillez utiliser le lien suivant pour vous connecter en mode sécurisé (https://)

avez-vous une idée, du soucis j'ai pensé à un autre module mais aucune erreur ne remonte dans les logs.Je vous remercie d'avance

**Comment by Klemart3D** [comment]
Salut @nicoxygen,
J'ai corrigé les redirections pour prendre en compte HTTPS : https://github.com/Klemart3D/changecarrier/commit/1fe8b4b33386ab46e1e37bda275847d25dd393c5
Peux-tu tester ça et me dire si ça corrige ton souci ?

**Comment by nicoxygen** [comment]
Merci ça fonctionne, ce qui est bizarre c'est que j'ai toujours eu le site en https et il n'y avait pas de soucis jusque là.
Bref merci.
